//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Columns {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Columns() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Columns", typeof(Columns).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountCode.
        /// </summary>
        public static string AccountCode {
            get {
                return ResourceManager.GetString("AccountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountFloatingCode.
        /// </summary>
        public static string AccountFloatingCode {
            get {
                return ResourceManager.GetString("AccountFloatingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountFloatingCode2.
        /// </summary>
        public static string AccountFloatingCode2 {
            get {
                return ResourceManager.GetString("AccountFloatingCode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountFloatingCode3.
        /// </summary>
        public static string AccountFloatingCode3 {
            get {
                return ResourceManager.GetString("AccountFloatingCode3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountFloatingId.
        /// </summary>
        public static string AccountFloatingId {
            get {
                return ResourceManager.GetString("AccountFloatingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountFloatingTitle.
        /// </summary>
        public static string AccountFloatingTitle {
            get {
                return ResourceManager.GetString("AccountFloatingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountFloatingTitle2.
        /// </summary>
        public static string AccountFloatingTitle2 {
            get {
                return ResourceManager.GetString("AccountFloatingTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountFloatingTitle3.
        /// </summary>
        public static string AccountFloatingTitle3 {
            get {
                return ResourceManager.GetString("AccountFloatingTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountId.
        /// </summary>
        public static string AccountId {
            get {
                return ResourceManager.GetString("AccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountTitle.
        /// </summary>
        public static string AccountTitle {
            get {
                return ResourceManager.GetString("AccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CostCenterId.
        /// </summary>
        public static string CostCenterId {
            get {
                return ResourceManager.GetString("CostCenterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedBy.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        public static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrencyId.
        /// </summary>
        public static string CurrencyId {
            get {
                return ResourceManager.GetString("CurrencyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrencyTitle.
        /// </summary>
        public static string CurrencyTitle {
            get {
                return ResourceManager.GetString("CurrencyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentTypeId.
        /// </summary>
        public static string DocumentTypeId {
            get {
                return ResourceManager.GetString("DocumentTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullCode.
        /// </summary>
        public static string FullCode {
            get {
                return ResourceManager.GetString("FullCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullTitle.
        /// </summary>
        public static string FullTitle {
            get {
                return ResourceManager.GetString("FullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifiedBy.
        /// </summary>
        public static string ModifiedBy {
            get {
                return ResourceManager.GetString("ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        public static string Modifier {
            get {
                return ResourceManager.GetString("Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
