//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای دسترسی.
        /// </summary>
        public static string Authorize {
            get {
                return ResourceManager.GetString("Authorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما قادر به دسترسی به این بخش نمی باشید.
        /// </summary>
        public static string AuthorizeDescription {
            get {
                return ResourceManager.GetString("AuthorizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انواع داده غیرهمجنس - عدم قابلیت تبدیل.
        /// </summary>
        public static string Cast {
            get {
                return ResourceManager.GetString("Cast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی هنگام تبدیل نوع داده غیرهمسان رخ داده است. مثلا قراردادن یک مقدار متنی در متغیر عددی میتواند باعث بروز چنین مشکلی شود.
        /// </summary>
        public static string CastDescription {
            get {
                return ResourceManager.GetString("CastDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عامل بروز عدم هماهنگی داده ها.
        /// </summary>
        public static string Conflict {
            get {
                return ResourceManager.GetString("Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودیت مورد نظر در گردش می باشد. محل گردش: {0}.
        /// </summary>
        public static string ConflictDescription {
            get {
                return ResourceManager.GetString("ConflictDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عامل بروز داده های تکراری.
        /// </summary>
        public static string Constraint {
            get {
                return ResourceManager.GetString("Constraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده وارد شده در بانک اطلاعاتی موجود میباشد. در صورت درج مجدد این اطلاعات، داده های تکراری خواهید داشت..
        /// </summary>
        public static string ConstraintDescription {
            get {
                return ResourceManager.GetString("ConstraintDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این شماره به سند دیگری اختصاص داده شده است.
        /// </summary>
        public static string DocumentNumberIsUse {
            get {
                return ResourceManager.GetString("DocumentNumberIsUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidAuthorizationHeader.
        /// </summary>
        public static string InvalidAuthorizationHeader {
            get {
                return ResourceManager.GetString("InvalidAuthorizationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل انتخاب شده مجاز نمی باشد، پسوندهای مجاز عبارتند از: {0}.
        /// </summary>
        public static string InvalidExtension {
            get {
                return ResourceManager.GetString("InvalidExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissingAuthorizationHeader.
        /// </summary>
        public static string MissingAuthorizationHeader {
            get {
                return ResourceManager.GetString("MissingAuthorizationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع گزارش انتخابی شما تعریف نشده است..
        /// </summary>
        public static string UnknownTypeToExport {
            get {
                return ResourceManager.GetString("UnknownTypeToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر محدودیت زمانی دارد.
        /// </summary>
        public static string UserHasTimeLimit {
            get {
                return ResourceManager.GetString("UserHasTimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر غیرفعال است.
        /// </summary>
        public static string UserIsInActive {
            get {
                return ResourceManager.GetString("UserIsInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر قفل شده است.
        /// </summary>
        public static string UserIsLocked {
            get {
                return ResourceManager.GetString("UserIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا کلمه عبور اشتباه است.
        /// </summary>
        public static string UsernameOrPasswordIsInvalid {
            get {
                return ResourceManager.GetString("UsernameOrPasswordIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر یافت نشد.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
