//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب صحیح میباشد.
        /// </summary>
        public static string AccountNumberIsCorrect {
            get {
                return ResourceManager.GetString("AccountNumberIsCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب متعلق به شخص مورد نظر نیست.
        /// </summary>
        public static string AccountNumberIsInCorrect {
            get {
                return ResourceManager.GetString("AccountNumberIsInCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب نباید تکراری وارد شود.
        /// </summary>
        public static string AccountNumberMustBeNotDuplicate {
            get {
                return ResourceManager.GetString("AccountNumberMustBeNotDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای جستجوی اشخاص  نام یا نام خانوادگی یا عنوان یا کد ملی و یا شناسه ملی شرکت را وارد نمایید.
        /// </summary>
        public static string AccountSearchPersons {
            get {
                return ResourceManager.GetString("AccountSearchPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس باید قالب شاپرکی داشته باشد.
        /// </summary>
        public static string AddressMustBeShaparak {
            get {
                return ResourceManager.GetString("AddressMustBeShaparak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از حذف اطلاعات اطمینان دارید؟.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی در سرور رخ داده است..
        /// </summary>
        public static string AServerErrorOccurred {
            get {
                return ResourceManager.GetString("AServerErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به دلیل در وضعیت تایید بودن قابل ویرایش نیست.
        /// </summary>
        public static string CanNotBeEditInConfirmed {
            get {
                return ResourceManager.GetString("CanNotBeEditInConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صاحب امتیاز باید حداقل یک آدرس &quot;{0}&quot; داشته باشد.
        /// </summary>
        public static string CertificateOwnerMustHaveOneAddressCategory {
            get {
                return ResourceManager.GetString("CertificateOwnerMustHaveOneAddressCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صاحب امتیاز باید حداقل یک تلفن &quot;{0}&quot; داشته باشد.
        /// </summary>
        public static string CertificateOwnerMustHaveOnePhoneType {
            get {
                return ResourceManager.GetString("CertificateOwnerMustHaveOnePhoneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلیک کنید..
        /// </summary>
        public static string Click {
            get {
                return ResourceManager.GetString("Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای نمایش جزئیات خطا کلیک کنید..
        /// </summary>
        public static string ClickForShowError {
            get {
                return ResourceManager.GetString("ClickForShowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم هایی که با رنگ قرمز مشخص شده اند، از نظر تعداد تخصیص داده شده دارای اشکال می باشند.
        /// </summary>
        public static string ColoredItemsHasErrorsInAssignments {
            get {
                return ResourceManager.GetString("ColoredItemsHasErrorsInAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور و تایید رمزعبور یکسان نیستند.
        /// </summary>
        public static string ConfirmPasswordIncorrect {
            get {
                return ResourceManager.GetString("ConfirmPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطاهای گزارش شده را برطرف نمایید.
        /// </summary>
        public static string CorrectReportedErrors {
            get {
                return ResourceManager.GetString("CorrectReportedErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات حذف گردید.
        /// </summary>
        public static string DataIsDeleted {
            get {
                return ResourceManager.GetString("DataIsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از حذف «{title}» اطمینان دارید؟.
        /// </summary>
        public static string DeleteWithTitle {
            get {
                return ResourceManager.GetString("DeleteWithTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای انتساب اشخاص به پست های سازمانی بر روی سطر مورد دابل کلیک کرده یا روی عنوان پست کلیک کنید .
        /// </summary>
        public static string DoubleClickOnRowsToAssignPersons {
            get {
                return ResourceManager.GetString("DoubleClickOnRowsToAssignPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصه هایی را که میخواهید در فایل خروجی وجود داشته باشند، با زدن تیک مشخص کنید.
        /// </summary>
        public static string ExportFieldsHelp {
            get {
                return ResourceManager.GetString("ExportFieldsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحوه نمایش مشخصه هایی را که ممکن است چند مقدار داشته باشند، با انتخاب «جداساز» یا «سطرهای جدا» مشخص کنید.
        /// </summary>
        public static string ExportMultiValueHelp {
            get {
                return ResourceManager.GetString("ExportMultiValueHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به وسیله فلشها ترتیب نمایش مشخصه ها در خروجی را مشخص کنید.
        /// </summary>
        public static string ExportReOrderHelp {
            get {
                return ResourceManager.GetString("ExportReOrderHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیدا کردن ودیعه های مشابه.
        /// </summary>
        public static string FindSimilarTrust {
            get {
                return ResourceManager.GetString("FindSimilarTrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی رخ داده است.
        /// </summary>
        public static string HasError {
            get {
                return ResourceManager.GetString("HasError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمیتوانم وارد حسابم شوم!!.
        /// </summary>
        public static string ICantLogin {
            get {
                return ResourceManager.GetString("ICantLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا سطح آخر را انتخاب نمایید که با رنگ سبز مشخص شده اند..
        /// </summary>
        public static string MerchantCategorySelectionHelp {
            get {
                return ResourceManager.GetString("MerchantCategorySelectionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پذیرنده باید حداقل یک آدرس &quot;{0}&quot; داشته باشد.
        /// </summary>
        public static string MerchantMustHaveOneAddressCategory {
            get {
                return ResourceManager.GetString("MerchantMustHaveOneAddressCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پذیرنده باید حداقل یک تلفن &quot;{0}&quot; داشته باشد.
        /// </summary>
        public static string MerchantMustHaveOnePhoneType {
            get {
                return ResourceManager.GetString("MerchantMustHaveOnePhoneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باید حداقل یک &quot;{0}&quot; داشته باشد.
        /// </summary>
        public static string MustHave {
            get {
                return ResourceManager.GetString("MustHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} باید حداقل یک آدرس &quot;{0}&quot; داشته باشد.
        /// </summary>
        public static string MustHaveOneAddressCategory {
            get {
                return ResourceManager.GetString("MustHaveOneAddressCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} باید حداقل یک تلفن &quot;{0}&quot; داشته باشد.
        /// </summary>
        public static string MustHaveOnePhoneType {
            get {
                return ResourceManager.GetString("MustHaveOnePhoneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجوزی تعریف نشده است.
        /// </summary>
        public static string NotDefinePermission {
            get {
                return ResourceManager.GetString("NotDefinePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شخصی انتخاب نشده است.
        /// </summary>
        public static string NotSelectedPerson {
            get {
                return ResourceManager.GetString("NotSelectedPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست با کدرهگیری: {0} ثبت شد.
        /// </summary>
        public static string RequestSumbited {
            get {
                return ResourceManager.GetString("RequestSumbited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال با موفقیت انجام شد.
        /// </summary>
        public static string SuccessSent {
            get {
                return ResourceManager.GetString("SuccessSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استفاده کننده باید حداقل یک آدرس &quot;{0}&quot; داشته باشد.
        /// </summary>
        public static string UsedByPersonMustHaveOneAddressCategory {
            get {
                return ResourceManager.GetString("UsedByPersonMustHaveOneAddressCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استفاده کننده باید حداقل یک تلفن &quot;{0}&quot; داشته باشد.
        /// </summary>
        public static string UsedByPersonMustHaveOnePhoneType {
            get {
                return ResourceManager.GetString("UsedByPersonMustHaveOnePhoneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وبسایت مورد نظر حتما باید صاحب امتیاز داشته باشد.
        /// </summary>
        public static string WebsiteMustHaveOwner {
            get {
                return ResourceManager.GetString("WebsiteMustHaveOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی صحیح نیست.
        /// </summary>
        public static string WrongNationalCode {
            get {
                return ResourceManager.GetString("WrongNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما {0} ترمینال آماده برای انتساب قرارداد دارید.
        /// </summary>
        public static string YouHaveTerminalOnAssignment {
            get {
                return ResourceManager.GetString("YouHaveTerminalOnAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما {0} ترمینال در وضعیت نیاز به بررسی دارید.
        /// </summary>
        public static string YouHaveTerminalOnReviewNeeded {
            get {
                return ResourceManager.GetString("YouHaveTerminalOnReviewNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حد اقل یک قابلیت باید انتخاب گردد.
        /// </summary>
        public static string YouMustSlectOneFacility {
            get {
                return ResourceManager.GetString("YouMustSlectOneFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک ردیف را انتخاب کنید.
        /// </summary>
        public static string YouMustSlectOneRow {
            get {
                return ResourceManager.GetString("YouMustSlectOneRow", resourceCulture);
            }
        }
    }
}
