//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Validations", typeof(Validations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب باید از لیست انتخاب شود.
        /// </summary>
        public static string AccountNumberShouldBeSelectedFromSuggestion {
            get {
                return ResourceManager.GetString("AccountNumberShouldBeSelectedFromSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد کردن محل های آدرس الزامی است.
        /// </summary>
        public static string AddressElementsRequired {
            get {
                return ResourceManager.GetString("AddressElementsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل یک پایانه باید انتخاب شده باشد.
        /// </summary>
        public static string AtLeastOneDeviceTypeMustBeSelected {
            get {
                return ResourceManager.GetString("AtLeastOneDeviceTypeMustBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل یک قابلیت باید انتخاب شده باشد.
        /// </summary>
        public static string AtLeastOneFeatureMustBeSelected {
            get {
                return ResourceManager.GetString("AtLeastOneFeatureMustBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایلهای بزرگتر از {0}KB را نمی توان آپلود کرد.
        /// </summary>
        public static string CantUploadFileLargerThanX {
            get {
                return ResourceManager.GetString("CantUploadFileLargerThanX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قالب تاریخ ورودی صحیح نمی باشد.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قالب تاریخ و زمان ورودی صحیح نمی باشد.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قالب تاریخ و زمان ورودی برای &quot;{title}&quot; صحیح نمی باشد.
        /// </summary>
        public static string DateTimeWithTitle {
            get {
                return ResourceManager.GetString("DateTimeWithTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قالب تاریخ ورودی برای &quot;{title}&quot; صحیح نمی باشد.
        /// </summary>
        public static string DateWithTitle {
            get {
                return ResourceManager.GetString("DateWithTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در یک سطح سازمانی نمی توان دو پست هم نام داشت.
        /// </summary>
        public static string DuplicateOrganizationPost {
            get {
                return ResourceManager.GetString("DuplicateOrganizationPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقعیت آدرس تکراری میباشد.
        /// </summary>
        public static string DupplicateAddressElementvalidationError {
            get {
                return ResourceManager.GetString("DupplicateAddressElementvalidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید {0} حرف باشد.
        /// </summary>
        public static string FixedLength {
            get {
                return ResourceManager.GetString("FixedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده برای {title} باید {0} حرف باشد.
        /// </summary>
        public static string FixedLengthWithTitle {
            get {
                return ResourceManager.GetString("FixedLengthWithTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار ورودی مجاز نمی باشد.
        /// </summary>
        public static string Fn {
            get {
                return ResourceManager.GetString("Fn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار ورودی برای {title} مجاز نمی باشد.
        /// </summary>
        public static string FnWithTitle {
            get {
                return ResourceManager.GetString("FnWithTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قالب IP وارد شده صحیح نمی باشد.
        /// </summary>
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر تعداد کاراکتر ورودی {0} عدد می باشد.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر تعداد کاراکتر ورودی {title} {0} عدد می باشد.
        /// </summary>
        public static string MaxLengthWithTitle {
            get {
                return ResourceManager.GetString("MaxLengthWithTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل تعداد کاراکتر ورودی {0} عدد می باشد.
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل تعداد کاراکتر ورودی {title} {0} عدد می باشد.
        /// </summary>
        public static string MinLengthWithTitle {
            get {
                return ResourceManager.GetString("MinLengthWithTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای {0} نمی توان بیش از یک فایل آپلود کرد.
        /// </summary>
        public static string MultipleFileUploadingIsNotAllowed {
            get {
                return ResourceManager.GetString("MultipleFileUploadingIsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار نمیتواند خالی باشد.
        /// </summary>
        public static string NotEmpty {
            get {
                return ResourceManager.GetString("NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط مقادیر عددی وارد نمایید.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار {title} باید عددی باشد.
        /// </summary>
        public static string NumberWithTitle {
            get {
                return ResourceManager.GetString("NumberWithTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدپستی باید 10 رقم باشد.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قالب مقدار وارد شده صحیح نمی باشد.
        /// </summary>
        public static string Regex {
            get {
                return ResourceManager.GetString("Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قالب مقدار وارد شده برای {title} صحیح نمی باشد.
        /// </summary>
        public static string RegexWithTitle {
            get {
                return ResourceManager.GetString("RegexWithTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد کردن مقدار برای این فیلد الزامی است.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد کردن {title} الزامی است.
        /// </summary>
        public static string RequiredWithTitle {
            get {
                return ResourceManager.GetString("RequiredWithTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد سهم نمی تواند بیشتر از 100 باشد.
        /// </summary>
        public static string ShareCannotBeMoreThan100 {
            get {
                return ResourceManager.GetString("ShareCannotBeMoreThan100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد کردن توضیحات الزامی است.
        /// </summary>
        public static string StatusDescription {
            get {
                return ResourceManager.GetString("StatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمع درصد سهم باید 100 باشد.
        /// </summary>
        public static string SumOfSharesMustBe100 {
            get {
                return ResourceManager.GetString("SumOfSharesMustBe100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قالب زمان ورودی صحیح نمی باشد.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قالب زمان ورودی برای &quot;{title}&quot; صحیح نمی باشد.
        /// </summary>
        public static string TimeWithTitle {
            get {
                return ResourceManager.GetString("TimeWithTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استفاده کننده حتما باید با ابزار فراهم شده انتخاب شود.
        /// </summary>
        public static string UsedByShouldBeSelected {
            get {
                return ResourceManager.GetString("UsedByShouldBeSelected", resourceCulture);
            }
        }
    }
}
